services:
  - type: web
    name: agrilume
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
